### ISSUE TITLE
[laravel 5.2.31] Target [anlutro\LaravelSettings\SettingStore] is not instantiable while building

### ISSUE THREAD

**Issue by zaffar-saffee** [anlutro/laravel-settings#48]
updating 5.2.31 gave me this error

```
Local.ERROR: Illuminate\Contracts\Container\BindingResolutionException: Target [anlutro\LaravelSettings\SettingStore] is not instantiable while building [anlutro\LaravelSettings\SettingsManager, anlutro\LaravelSettings\SaveMiddleware]. in /home/forge/staging.example.com/vendor/laravel/framework/src/Illuminate/Container/Container.php:752
Stack trace:
#0 /home/forge/staging.example.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(633): Illuminate\Container\Container->build('anlutro\\Laravel...', Array)
#1 /home/forge/staging.example.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\Container\Container->make('anlutro\\Laravel...', Array)
#2 /home/forge/staging.example.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(853): Illuminate\Foundation\Application->make('anlutro\\Laravel...')
#3 /home/forge/staging.example.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(808): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#4 /home/forge/staging.example.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(777): Illuminate\Container\Container->getDependencies(Array, Array)
#5 /home/forge/staging.example.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(633): Illuminate\Container\Container->build('anlutro\\Laravel...', Array)
#6 /home/forge/staging.example.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\Container\Container->make('anlutro\\Laravel...', Array)
#7 /home/forge/staging.example.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(152): Illuminate\Foundation\Application->make('anlutro\\Laravel...')
#8 /home/forge/staging.example.com/public/index.php(58): Illuminate\Foundation\Http\Kernel->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#9 {main}
```

See laravel/framework support for this
[#laravel/framework/issues/13347](https://github.com/laravel/framework/issues/13347)

**Comment by anlutro** [comment]
Did you add the middleware but not the service provider?

**Comment by zaffar-saffee** [comment]
I believe I have added the both, let me reconfirm it..

**Comment by zaffar-saffee** [comment]
I have all set up correctly, let me know if I am missing anything
```
 anlutro\LaravelSettings\ServiceProvider::class,
'Setting' => anlutro\LaravelSettings\Facade::class,

 protected $middleware = [
        \Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode::class,
        \anlutro\LaravelSettings\SaveMiddleware::class,
    ];
```

**Comment by anlutro** [comment]
No idea, then. For some reason the `terminate` method is running before the service provider has been registered.

**Comment by kirobo** [comment]
Same issue

**Comment by bweston92** [comment]
Was there a fix for this?
